### ISSUE TITLE
Update GitVersion Fix Regex

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/xPSDesiredStateConfiguration#660]
Update GitVersion Fixes Regex:
```yaml
  feature:
    tag: useBranchName
    increment: Minor
    regex: f(eature(s)?)?[\/-]
    source-branches: ['master']
  hotfix:
    tag: fix
    increment: Patch
    regex: (hot)?fix(es)?[\/-]
    source-branches: ['master']
```
