### ISSUE TITLE
Update GitVersion.yml to use latest pattern

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/xPSDesiredStateConfiguration#707]
Update `GitVersion.yml` branches section to:
```yml
branches:
  master:
    tag: preview
    regex: ^main$
  pull-request:
    tag: PR
  feature:
    tag: useBranchName
    increment: Minor
    regex: f(eature(s)?)?[\/-]
    source-branches: ['master']
  hotfix:
    tag: fix
    increment: Patch
    regex: (hot)?fix(es)?[\/-]
    source-branches: ['master']
```

As per: https://github.com/dsccommunity/dsccommunity.org/pull/162
